name: Paketit
favicon: null
layout_spectrum: 0.08629
typography_spectrum: 0.24432
title: OMAN TEKEMISEN PARANTAMINEN AUTTAA AINA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22160a'
    - '#fe9341'
    - '#8f9587'
    - '#404f56'
  brandStrength: 0.375
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
